// <auto-generated />
using System;
using BrewAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrewAPI.Migrations
{
    [DbContext(typeof(BrewAPIDbContext))]
    [Migration("20250901184421_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrewAPI.Models.Booking", b =>
                {
                    b.Property<int>("PK_BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_BookingId"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("BookingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DurationTime")
                        .HasColumnType("time");

                    b.Property<int>("FK_CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FK_TableId")
                        .HasColumnType("int");

                    b.Property<int>("NumberGuests")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.HasKey("PK_BookingId");

                    b.HasIndex("FK_CustomerId");

                    b.HasIndex("FK_TableId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            PK_BookingId = 1,
                            BookingDate = new DateOnly(2025, 9, 2),
                            BookingTime = new TimeOnly(18, 30, 0),
                            DurationTime = new TimeSpan(0, 2, 0, 0, 0),
                            FK_CustomerId = 1,
                            FK_TableId = 1,
                            NumberGuests = 2,
                            Status = "Confirmed"
                        },
                        new
                        {
                            PK_BookingId = 2,
                            BookingDate = new DateOnly(2025, 9, 3),
                            BookingTime = new TimeOnly(19, 0, 0),
                            DurationTime = new TimeSpan(0, 2, 0, 0, 0),
                            FK_CustomerId = 2,
                            FK_TableId = 3,
                            NumberGuests = 4,
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("BrewAPI.Models.Customer", b =>
                {
                    b.Property<int>("PK_CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_CustomerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PK_CustomerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            PK_CustomerId = 1,
                            Email = "test@exempel.com",
                            Name = "Test Testsson",
                            PhoneNumber = "070-1234567"
                        },
                        new
                        {
                            PK_CustomerId = 2,
                            Email = "tian@exempel.com",
                            Name = "Tian Tiansson",
                            PhoneNumber = "076-1234567"
                        });
                });

            modelBuilder.Entity("BrewAPI.Models.MenuItem", b =>
                {
                    b.Property<int>("PK_MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_MenuItemId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("PK_MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            PK_MenuItemId = 1,
                            Category = "Salads",
                            Description = "Handskalade räkor, bacon, cocktailtomat, rostade kruttonger, picklad rödlök, grana padano",
                            ImageUrl = "https://unsplash.com/photos/vegetable-salad-on-white-ceramic-bowl-gOJxrVvhCF8",
                            IsPopular = true,
                            Name = "Ceasarsallad Räkor",
                            Price = 145.00m
                        },
                        new
                        {
                            PK_MenuItemId = 2,
                            Category = "Salads",
                            Description = "Svensk kyckling, caesar dressing, rödlök, ugnsbakade cocktailtomater, parmesan, & egenrostade krutonger",
                            ImageUrl = "https://unsplash.com/photos/vegetable-salad-pCxJvSeSB5A",
                            IsPopular = true,
                            Name = "Ceasarsallad",
                            Price = 145.00m
                        },
                        new
                        {
                            PK_MenuItemId = 3,
                            Category = "Salads",
                            Description = "Halstrad tonfiskfilé med sallad citron & korianderkräm",
                            ImageUrl = "https://unsplash.com/photos/vegetable-salad-on-white-ceramic-bowl-LJ49dflDcH8",
                            IsPopular = false,
                            Name = "Tonfisksallad",
                            Price = 145.00m
                        },
                        new
                        {
                            PK_MenuItemId = 4,
                            Category = "Salads",
                            Description = "Rostade valnötter, fikon, rödbetor, äpple och rädisor, cocktailtomater, honung, ärtskott.",
                            ImageUrl = "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400",
                            IsPopular = false,
                            Name = "Chevré Salad",
                            Price = 125.00m
                        },
                        new
                        {
                            PK_MenuItemId = 5,
                            Category = "Bowls",
                            Description = "Bulgogimarinerat högrev, bakat ägg, kimchi, morötter, spenat, böngroddar, furikake, sesamfrön, gochujangsås, sojamayo",
                            ImageUrl = "https://unsplash.com/photos/vegetable-and-meat-on-bowl-kcA-c3f_3FE",
                            IsPopular = true,
                            Name = "Din-Din Bap Bowl",
                            Price = 188.00m
                        },
                        new
                        {
                            PK_MenuItemId = 6,
                            Category = "Bowls",
                            Description = "Kycklinglårfilé, ris, mango, teriyaksås, sojamajo, salladslök, togarashi, chili, soja, avokado, sojabönor, kimchi, picklad rödkål, smashed spicy cucumber",
                            ImageUrl = "https://unsplash.com/photos/vegetable-and-meat-on-bowl-kcA-c3f_3FE",
                            IsPopular = false,
                            Name = "Sneaky Samurai Bowl",
                            Price = 164.00m
                        },
                        new
                        {
                            PK_MenuItemId = 7,
                            Category = "Bowls",
                            Description = "Kycklinglårfilé, ris, mango, teriyaksås, sojamajo, salladslök, togarashi, chili, soja, avokado, sojabönor, kimchi, picklad rödkål, smashed spicy cucumber",
                            ImageUrl = "Gochujangmarienerad, Karaage-kyckling, ris, picklad rödkål, soja, avokado, sojabönor, kimichi, svart sesamfrö, gräslök , smashed spicy cucumber",
                            IsPopular = false,
                            Name = "Karaage Bowl",
                            Price = 164.00m
                        },
                        new
                        {
                            PK_MenuItemId = 8,
                            Category = "Desserts",
                            Description = "Fransk crêpe med pistagekräm, choklad och vaniljglass",
                            ImageUrl = "https://unsplash.com/photos/a-person-cooking-pancakes-in-a-pan-on-a-stove-465ZLD7Ia2s",
                            IsPopular = true,
                            Name = "Dubai chocolate crêpe",
                            Price = 85.00m
                        },
                        new
                        {
                            PK_MenuItemId = 9,
                            Category = "Desserts",
                            Description = "Frasig croissant bakad med smör",
                            ImageUrl = "https://unsplash.com/photos/a-person-cooking-pancakes-in-a-pan-on-a-stove-465ZLD7Ia2s",
                            IsPopular = false,
                            Name = "Croissant",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 10,
                            Category = "Desserts",
                            Description = "Vetebulle bakad med surdeg, fylld med pumpafyllning och toppad med majssmulor.",
                            ImageUrl = "https://unsplash.com/photos/brown-bread-on-brown-wooden-chopping-board-UaU8hu9IJQY",
                            IsPopular = false,
                            Name = "Pumpkin Bun",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 11,
                            Category = "Desserts",
                            Description = "Kladdkaka som serveras med vispgrädde och vaniljglass",
                            ImageUrl = "https://unsplash.com/photos/a-plate-with-a-piece-of-cake-and-berries-on-it-JXEzhndND7I",
                            IsPopular = true,
                            Name = "Mudcake",
                            Price = 65.00m
                        },
                        new
                        {
                            PK_MenuItemId = 12,
                            Category = "Desserts",
                            Description = "En rund kak- och gräddmousse med chokladsmulor",
                            ImageUrl = "https://unsplash.com/photos/a-person-holding-a-spoon-with-a-dessert-on-it-NuATPGDYSIw",
                            IsPopular = true,
                            Name = "Moussekaka Cookies & Cream",
                            Price = 65.00m
                        },
                        new
                        {
                            PK_MenuItemId = 13,
                            Category = "Beverages",
                            Description = "Krämig cappuccino med perfekt mjölkskum",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
                            IsPopular = false,
                            Name = "Cappuccino",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 14,
                            Category = "Beverages",
                            Description = "Sötat grönt matchate, serverat med kall havredryck och is",
                            ImageUrl = "https://unsplash.com/photos/a-shot-glass-filled-with-green-liquid-on-top-of-a-wooden-table-N1rmKN_EOaA",
                            IsPopular = true,
                            Name = "Ismatcha",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 15,
                            Category = "Beverages",
                            Description = "Espresso blandat med kall mjölk och is",
                            ImageUrl = "https://unsplash.com/photos/clear-glass-filled-ice-coffee-vZOZJH_xkUk",
                            IsPopular = false,
                            Name = "Iced Latte",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 16,
                            Category = "Beverages",
                            Description = "Espresso blandat med mjölk",
                            ImageUrl = "https://unsplash.com/photos/closeup-photo-of-coffee-wecVUUVopRY",
                            IsPopular = false,
                            Name = "Latte",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 17,
                            Category = "Beverages",
                            Description = "Blonde Roast - Veranda Blend",
                            ImageUrl = "https://unsplash.com/photos/white-ceramic-teacup-with-coffee-beans-lsmu0rUhUOk",
                            IsPopular = false,
                            Name = "Hot Coffee",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 18,
                            Category = "Beverages",
                            Description = "Vaniljshake med smak av choklad. Toppad med vispgrädde",
                            ImageUrl = "https://unsplash.com/photos/chocolate-cookie-frappe-4FujjkcI40g",
                            IsPopular = true,
                            Name = "Caramel Frappuccino",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 19,
                            Category = "Beverages",
                            Description = "Kaffeshake med smak av kola. Toppad med vispgrädde",
                            ImageUrl = "https://unsplash.com/photos/a-close-up-of-a-cup-of-food-on-a-table-OSYt_g-EoPE",
                            IsPopular = false,
                            Name = "Caramel Frappuccino",
                            Price = 45.00m
                        },
                        new
                        {
                            PK_MenuItemId = 20,
                            Category = "Beverages",
                            Description = "Grönt, svart eller rött té i olika smaker",
                            ImageUrl = "https://unsplash.com/photos/a-person-pours-tea-into-a-cup-XbYnaCbUWnI",
                            IsPopular = false,
                            Name = "Tea Selection",
                            Price = 40.00m
                        });
                });

            modelBuilder.Entity("BrewAPI.Models.Table", b =>
                {
                    b.Property<int>("PK_TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("PK_TableId");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            PK_TableId = 1,
                            Capacity = 2,
                            IsAvailable = true,
                            TableNumber = 1
                        },
                        new
                        {
                            PK_TableId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableNumber = 2
                        },
                        new
                        {
                            PK_TableId = 3,
                            Capacity = 6,
                            IsAvailable = true,
                            TableNumber = 3
                        },
                        new
                        {
                            PK_TableId = 4,
                            Capacity = 8,
                            IsAvailable = true,
                            TableNumber = 4
                        },
                        new
                        {
                            PK_TableId = 5,
                            Capacity = 2,
                            IsAvailable = true,
                            TableNumber = 5
                        },
                        new
                        {
                            PK_TableId = 6,
                            Capacity = 4,
                            IsAvailable = true,
                            TableNumber = 6
                        });
                });

            modelBuilder.Entity("BrewAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "test@exempel.com",
                            FirstName = "Johannes",
                            LastName = "Brannelid",
                            PasswordHash = "$2a$11$8Xl3E5qDNqK0rV2QcMkV4eJ1Q8P7K9zF0nR6tY3sW2hA5cU1mB7dO",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("BrewAPI.Models.Booking", b =>
                {
                    b.HasOne("BrewAPI.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("FK_CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrewAPI.Models.Table", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("FK_TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("BrewAPI.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BrewAPI.Models.Table", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
